dataset_name: PBMC_paired
dataset_dir: ../../data/PBMC_paired
GAM_name: ArchR
dataset_type: RNA_ATAC
batch: None
paired: True

n_high_var: 2000
dim: 100
neighbors_mnn: 200
use_rep: hvg_count #[hvg_count, hvg_norm, low_emb]
latent_dim: 50

tau_cell: 0.5
tau_feature: 10
alpha: 10000
beta: 10000
gamma_a: 1
gamma_b: 1
metric: cosine

seed: 123
batch_size: 256
learning_rate: 0.0001
weight_decay: 0.00005
epoch: 1000



