dataset_name: PBMC
dataset_dir: ../data/PBMC
GAM_name: ArchR
dataset_type: RNA_ATAC
batch: None
paired: True

n_high_var: 2000
dim: 100
neighbors_mnn: 500
metric: cosine
use_rep: hvg_count #[hvg_count, hvg_norm, low_emb]
latent_dim: 50

tau_cell: 0.5
tau_feature: 50
alpha: 1000000
beta: 10000


seed: 123
batch_size: 256
learning_rate: 0.0001
weight_decay: 0.00005
epoch: 1000



